
import { jsPDF } from "jspdf";
import { ChatSession } from "../types";

export const generatePDF = async (session: ChatSession) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFillColor(33, 150, 243); // Blue
    doc.rect(0, 0, 210, 20, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.text("MedScan AI - Clinical Consultation Record", 10, 13);
    
    // Patient Details
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 10, 30);
    doc.text(`Patient Summary: ${session.patientSummary.ageGroup}, ${session.patientSummary.sex}`, 10, 38);
    
    let yPos = 50;

    // Iterate through messages
    session.messages.forEach((msg) => {
        if (yPos > 270) {
            doc.addPage();
            yPos = 20;
        }

        const role = msg.role === 'user' ? "Patient/User" : "AI Assistant";
        doc.setFont("helvetica", "bold");
        doc.text(`${role} (${new Date(msg.timestamp).toLocaleTimeString()}):`, 10, yPos);
        yPos += 7;

        doc.setFont("helvetica", "normal");
        const lines = doc.splitTextToSize(msg.text, 190);
        doc.text(lines, 10, yPos);
        yPos += (lines.length * 7) + 5;

        // Add structured data if present
        if (msg.role === 'model' && msg.structuredResponse) {
             if (yPos > 250) { doc.addPage(); yPos = 20; }
             
             // Diagnosis box
             doc.setFillColor(240, 240, 240);
             doc.rect(10, yPos, 190, 40, 'F');
             doc.setFontSize(10);
             doc.text("Top Differential Diagnoses:", 15, yPos + 8);
             
             let dy = yPos + 15;
             msg.structuredResponse.differentialDiagnosis.slice(0, 3).forEach(dx => {
                 doc.text(`- ${dx.condition} (${dx.confidence}%)`, 15, dy);
                 dy += 5;
             });
             
             yPos += 45;
             doc.setFontSize(12);
        }
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by MedScan AI. This document is for informational purposes only.", 10, 290);

    doc.save(`MedScan_Report_${Date.now()}.pdf`);
};
